In [13]:
import sys
import os
import arcpy
HSMPY_PATH = r'\\CHCFPP01\Guest\MRajabi\Python Scripts'
sys.path.append(HSMPY_PATH)
import hsmpy3
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.core.display import HTML

In [2]:
IRISPath = r'\\CHCFPP01\Proj\ILDOT\650511SAFETYPROGRAM\4_WorkData\WO19\IL_Crash_Assignment\IRIS_Original'
Years = range(2004,2018)

In [15]:
IRIS_Shp   = {y:os.path.join(IRISPath,'HWY'+str(y)+'.shp') for y in Years}
df = pd.DataFrame(columns=Years)
for y in Years:
    LF = [F.name for F in arcpy.ListFields(IRIS_Shp[y])]
    for f in LF:
        df.set_value(f,y,1)
df = df.fillna(' ')
df = df.sort_index()
HTML(df.to_html())

In [16]:
df.loc[['MARKED_RT','MARKED_RT2','MARKED_RT3','MARKED_RT4','MRK_RT_TYP','MRK_RT_TY2','MRK_RT_TY3','MRK_RT_TY4','ROAD_NAME']]

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
MARKED_RT,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARKED_RT2,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARKED_RT3,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARKED_RT4,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MRK_RT_TYP,1,1,1,1,1,1,1,1,,,,,1,1
MRK_RT_TY2,1,1,1,1,1,1,1,1,,,,,1,1
MRK_RT_TY3,1,1,1,1,1,1,1,1,,,,,1,1
MRK_RT_TY4,1,1,1,1,1,1,1,1,,,,,1,1
ROAD_NAME,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [18]:
df.loc[['AADT','SU_VOL','MU_VOL','HCV','AADT_YR','HCV_MU_YR','SURF_YR']]

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
AADT,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SU_VOL,,1,1,1,1,1,1,1,1,1,1,1,1,1
MU_VOL,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HCV,1,1,1,1,1,1,1,1,1,1,1,1,1,1
AADT_YR,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HCV_MU_YR,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SURF_YR,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [25]:
display(df.loc[['FUNC_CLASS','FC','URBAN']])
display(df.loc[['ACC_CNTL','TOLL','TRK_RT']])
display(df.loc[['I_SHD1_TYP', 'I_SHD2_TYP','O_SHD1_TYP', 'O_SHD2_TYP',
        'I_SHD1_WTH', 'I_SHD2_WTH','O_SHD1_WTH', 'O_SHD2_WTH', 
        'MED_TYP', 'MED_WTH', 
         'LNS','LANES','LN_SPC_NBR', 
        'LN_WTH', 'LN_SPC_WTH', 
     'SURF_TYP', 'SURF_WTH','SURFACE1',
       'PRK_LT', 'PRK_RT' ]])

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
FUNC_CLASS,,,,,,,,,1,1,1,1,,
FC,1,1,1,1,1,1,1,1,,,,,1,1
URBAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1

         2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
ACC_CNTL    1    1    1    1    1    1    1    1    1    1    1    1    1    1
TOLL        1    1    1    1    1    1    1    1    1    1    1    1    1    1
TRK_RT      1    1    1    1    1    1    1    1    1    1    1    1    1    1

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
I_SHD1_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
I_SHD2_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
O_SHD1_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
O_SHD2_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
I_SHD1_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
I_SHD2_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
O_SHD1_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
O_SHD2_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MED_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MED_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LNS,1,1,1,1,1,1,1,1,,,1,1,1,1
LANES,,,,,,,,,1,1,1,1,,
LN_SPC_NBR,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LN_SPC_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SURF_TYP,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SURF_WTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SURFACE1,1,1,1,1,1,1,1,1,,,,,,
PRK_LT,1,1,1,1,1,1,1,1,1,1,1,1,1,1
PRK_RT,1,1,1,1,1,1,1,1,1,1,1,1,1,1